export const USER = {
    ADD    : 'ADD',
    GETALL : 'GETALL',
    UPDATE : 'UPDATE',
    DELETE : "DELETE",
    OPENADDUSERFORM : 'OPENADDUSERFORM',
    GETSINGLEUSER : 'GETSINGLEUSER',
    FORMOPERATION : 'FORMOPERATION'
}